questions = [
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    },
    {
        "question": ".",
        "effect": {
            "1auto": 0,
            "1demo": 0,
            "1auta": 0,
            "2prog": 0,
            "2trad": 0,
            "2libe": 0,
            "3comm": 0,
            "3coll": 0,
            "3mark": 0,
            "4impe": 0,
            "4worl": 0,
            "4isol": 0,
        }
    }
}
